[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=604800"